### ISSUE TITLE
moving cursor when no client is focused

### ISSUE THREAD

**Issue by vredesbyyrd** [basaran/awesomewm-micky#2]
Hello, thanks for sharing this module! I just switched to awesome from 2bwm and was glad to see 'cursor follows focus' is possible, although with the extensive lua api I suppose almost anything is possible :) 

I'm not sure this is a bug or intentional - When the cursor is not over a client, ie cursor is on the 'desktop', focusing a window (in my case with a keybinding) does not move the cursor to the newly focused client. 

I interpret the following function is supposed to handle this case?

```
if not client_under_mouse then
	micky()
	return false
end
```
if I am misinterpreting this, any hints to obtain the wanted behavior would be greatly appreciated. I'm slowly but steadily reading through awesomes api doc. 

Thanks for your time.

**Comment by basaran** [comment]
I see, could you try this slightly modified version?

```lua
client.connect_signal("focus", function(c)
    local focused_client = c
    --+ client the focus is going towards

    gears.timer.weak_start_new(0.15, function()
        local client_under_mouse = mouse.current_client

        if not client_under_mouse then
            micky()
            return false
        end
        --+ nothing under the mouse, just move the mouse

        local should_stay = set_contains(stay_classes, client_under_mouse.class)

        if should_stay then return false end
        --+ exclusions

        if focused_client:geometry().x ~= client_under_mouse:geometry().x
            or focused_client:geometry().y ~= client_under_mouse:geometry().y
        then
            micky()
            return false
        end
        --+ no need to relocate the mouse if already over
        --> the client.
    end)
    --+ mouse.current_client would point to the previous
    --> client without the callback.
end)
```

**Comment by vredesbyyrd** [comment]
That slight change does result in the wanted behavior :) I appreciate the help. Nicely implemented module btw.
